import { AlertCircle, CalendarDays, CheckCircle2, Clock, CreditCard, LayoutDashboard, MessageCircle, Settings, Users, Utensils, UtensilsCrossed, XCircle } from "lucide-react";

export const navigation = [
  {
    title: 'Geral',
    items: [
      {
        title: 'Painel',
        href: '/dashboard',
        icon: LayoutDashboard,
      },
      {
        title: 'Cardápio',
        href: '/dashboard/cardapio',
        icon: UtensilsCrossed,
      },
      {
        title: 'Reservas',
        href: '/dashboard/reservas',
        icon: CalendarDays,
      },
    ],
  },
  {
    title: 'Configurações',
    items: [
      {
        title: 'Restaurante',
        href: '/dashboard/configuracoes',
        icon: Settings,
      },
      {
        title: 'WhatsApp',
        href: '/dashboard/whatsapp',
        icon: MessageCircle,
      },
      {
        title: 'Plano',
        href: '/dashboard/plano',
        icon: CreditCard,
      },
    ],
  },
]

export const restaurants = [
  { id: '1', name: 'Cantina Bella Italia', slug: 'cantina-bella' },
  { id: '2', name: 'Sushi House Premium', slug: 'sushi-house' },
  { id: '3', name: 'Burger Lab', slug: 'burger-lab' },
]

export const stats = [
  {
    title: 'Reservas Hoje',
    value: '12',
    description: '3 pendentes de confirmação',
    icon: CalendarDays,
    trend: '+8% vs. semana passada',
  },
  {
    title: 'Próxima Reserva',
    value: '12:30',
    description: 'Mesa 4 - 4 pessoas',
    icon: Clock,
  },
  {
    title: 'Clientes Esperados',
    value: '45',
    description: 'Total do dia',
    icon: Users,
    trend: '+12% vs. semana passada',
  },
  {
    title: 'Itens no Cardápio',
    value: '68',
    description: '5 indisponíveis',
    icon: Utensils,
  },
]

export const upcomingReservations = [
  {
    id: '1',
    name: 'Maria Santos',
    phone: '+55 11 99999-0001',
    time: '12:30',
    guests: 4,
    table: 'Mesa 4',
    status: 'confirmed',
    note: 'Aniversário',
  },
  {
    id: '2',
    name: 'Carlos Oliveira',
    phone: '+55 11 99999-0002',
    time: '13:00',
    guests: 2,
    table: 'Mesa 7',
    status: 'pending',
  },
  {
    id: '3',
    name: 'Ana Costa',
    phone: '+55 11 99999-0003',
    time: '13:30',
    guests: 6,
    table: 'Mesa 12',
    status: 'confirmed',
  },
  {
    id: '4',
    name: 'Pedro Almeida',
    phone: '+55 11 99999-0004',
    time: '14:00',
    guests: 3,
    table: 'Mesa 2',
    status: 'pending',
    note: 'Cadeirante',
  },
  {
    id: '5',
    name: 'Fernanda Lima',
    phone: '+55 11 99999-0005',
    time: '19:00',
    guests: 8,
    table: 'Mesa 15',
    status: 'confirmed',
  },
  {
    id: '6',
    name: 'Ricardo Souza',
    phone: '+55 11 99999-0006',
    time: '20:00',
    guests: 2,
    table: 'Mesa 3',
    status: 'cancelled',
  },
]

export const categories = [
  { id: '1', name: 'Entradas', count: 8 },
  { id: '2', name: 'Pratos Principais', count: 15 },
  { id: '3', name: 'Massas', count: 12 },
  { id: '4', name: 'Pizzas', count: 18 },
  { id: '5', name: 'Sobremesas', count: 6 },
  { id: '6', name: 'Bebidas', count: 9 },
]

export const menuItems = [
  {
    id: '1',
    name: 'Bruschetta Tradicional',
    description: 'Pão italiano tostado com tomate fresco, manjericão e azeite extra virgem',
    price: 28.90,
    category: 'Entradas',
    available: true,
    image: null,
  },
  {
    id: '2',
    name: 'Carpaccio de Carne',
    description: 'Finas fatias de filé mignon com rúcula, alcaparras e lascas de parmesão',
    price: 45.90,
    category: 'Entradas',
    available: true,
    image: null,
  },
  {
    id: '3',
    name: 'Risotto de Funghi',
    description: 'Arroz arbóreo cremoso com mix de cogumelos frescos e parmesão',
    price: 68.90,
    category: 'Pratos Principais',
    available: true,
    image: null,
  },
  {
    id: '4',
    name: 'Filé à Parmegiana',
    description: 'Filé empanado com molho de tomate caseiro e queijo gratinado',
    price: 79.90,
    category: 'Pratos Principais',
    available: false,
    image: null,
  },
  {
    id: '5',
    name: 'Spaghetti Carbonara',
    description: 'Massa al dente com bacon crocante, ovo e queijo pecorino',
    price: 52.90,
    category: 'Massas',
    available: true,
    image: null,
  },
  {
    id: '6',
    name: 'Lasanha Bolonhesa',
    description: 'Camadas de massa fresca com ragú de carne e molho bechamel',
    price: 58.90,
    category: 'Massas',
    available: true,
    image: null,
  },
  {
    id: '7',
    name: 'Pizza Margherita',
    description: 'Molho de tomate San Marzano, mussarela de búfala e manjericão',
    price: 55.90,
    category: 'Pizzas',
    available: true,
    image: null,
  },
  {
    id: '8',
    name: 'Tiramisù',
    description: 'Sobremesa italiana clássica com café espresso e mascarpone',
    price: 32.90,
    category: 'Sobremesas',
    available: true,
    image: null,
  },
]

export const reservations = [
  {
    id: '1',
    name: 'Maria Santos',
    phone: '+55 11 99999-0001',
    email: 'maria@email.com',
    date: '2026-01-28',
    time: '12:30',
    guests: 4,
    table: 'Mesa 4',
    status: 'confirmed',
    note: 'Aniversário - trazer bolo às 14h',
    createdAt: '2026-01-25T10:00:00',
  },
  {
    id: '2',
    name: 'Carlos Oliveira',
    phone: '+55 11 99999-0002',
    email: 'carlos@email.com',
    date: '2026-01-28',
    time: '13:00',
    guests: 2,
    table: 'Mesa 7',
    status: 'pending',
    createdAt: '2026-01-27T15:30:00',
  },
  {
    id: '3',
    name: 'Ana Costa',
    phone: '+55 11 99999-0003',
    email: 'ana@email.com',
    date: '2026-01-28',
    time: '13:30',
    guests: 6,
    table: 'Mesa 12',
    status: 'confirmed',
    createdAt: '2026-01-26T09:15:00',
  },
  {
    id: '4',
    name: 'Pedro Almeida',
    phone: '+55 11 99999-0004',
    email: 'pedro@email.com',
    date: '2026-01-28',
    time: '14:00',
    guests: 3,
    table: 'Mesa 2',
    status: 'pending',
    note: 'Necessita cadeira de rodas',
    createdAt: '2026-01-27T18:00:00',
  },
  {
    id: '5',
    name: 'Fernanda Lima',
    phone: '+55 11 99999-0005',
    email: 'fernanda@email.com',
    date: '2026-01-28',
    time: '19:00',
    guests: 8,
    table: 'Mesa 15',
    status: 'confirmed',
    note: 'Reunião de negócios',
    createdAt: '2026-01-24T11:00:00',
  },
  {
    id: '6',
    name: 'Ricardo Souza',
    phone: '+55 11 99999-0006',
    email: 'ricardo@email.com',
    date: '2026-01-28',
    time: '20:00',
    guests: 2,
    table: 'Mesa 3',
    status: 'cancelled',
    createdAt: '2026-01-25T14:00:00',
  },
  {
    id: '7',
    name: 'Julia Mendes',
    phone: '+55 11 99999-0007',
    email: 'julia@email.com',
    date: '2026-01-28',
    time: '20:30',
    guests: 5,
    table: 'Mesa 8',
    status: 'confirmed',
    createdAt: '2026-01-26T16:30:00',
  },
  {
    id: '8',
    name: 'Lucas Pereira',
    phone: '+55 11 99999-0008',
    email: 'lucas@email.com',
    date: '2026-01-28',
    time: '21:00',
    guests: 4,
    table: 'Mesa 10',
    status: 'pending',
    createdAt: '2026-01-27T20:00:00',
  },
]

export const statusConfig = {
  confirmed: {
    label: 'Confirmada',
    variant: 'success' as const,
    icon: CheckCircle2,
  },
  pending: {
    label: 'Pendente',
    variant: 'warning' as const,
    icon: AlertCircle,
  },
  cancelled: {
    label: 'Cancelada',
    variant: 'secondary' as const,
    icon: XCircle,
  },
}